### ISSUE TITLE
Include option not to open a new window

### ISSUE THREAD

**Issue by raboof** [Kikobeats/tweet-selection#3]
but to just redirect to Twitter, might work better when people have popup blockers.

**Comment by Kikobeats** [comment]
Hmm I understood your point. Do you think that you can write a PR?

**Comment by raboof** [comment]
Sorry: what I saw was that when I clicked the twitter icon, the bubble would simply close.

I suspected this was due to the javascript and a popup blocker, but it turns out that had nothing to do with it: the problem was I bound to the 'body' element as suggested by the example, but that caused the 'onmousedown' event for opening the bubble to apply to the bubble itself, too... (if that makes any sense)

**Comment by Kikobeats** [comment]
then is not a issue? can we close? 😛

**Comment by raboof** [comment]
Merging the PR which improves the README.md not to suggest binding to `body` will automatically close it :)

**Comment by Kikobeats** [comment]
Perfect, thanks!
